export const INIT_COMMODITIES = "TRADE.INIT_COMMODITIES";
export const INIT_COUNTERPARTIES = "TRADE.INIT_COUNTERPARTIES";
export const INIT_LOCATIONS = "TRADE.INIT_LOCATIONS";
export const INIT_TRADES = "TRADE.INIT_TRADES";